
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgedjzqvaoghzjknopwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnZWRqenF2YW9naHpqa25vcHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5ODA4MTcsImV4cCI6MjA1NDU1NjgxN30.2Plxsyw44_ZUcwfjfh6rVyBQOpImxoUYt4wlThC4kAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
